# Generated by Django 2.0.1 on 2018-04-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('complaint', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='farmersignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FarmingTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FarmingName', models.CharField(max_length=50)),
                ('Farming_Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SellCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SuplierName', models.CharField(max_length=50)),
                ('CropName', models.CharField(max_length=40)),
                ('Quantity', models.CharField(max_length=20)),
                ('Rupees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='suppliersignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
