# Generated by Django 2.0.1 on 2018-04-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersignup',
            name='isFarmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliersignup',
            name='isSupplier',
            field=models.BooleanField(default=False),
        ),
    ]
