# Generated by Django 2.0.1 on 2018-04-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20180409_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_title', models.CharField(max_length=30)),
                ('Form_usage', models.CharField(max_length=30)),
                ('Form_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
